import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { TooltipProvider } from "@radix-ui/react-tooltip";
import { ClerkProvider } from "@clerk/nextjs"; // Skip Next.js internals and all static files, unless found in search params
import Navbar from "@/components/navbar";
import { ThemeProvider } from "@/context/theme";

const inter = Inter();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <TooltipProvider>
          <body className={`antialiased ${inter.className}`}>
            <ThemeProvider>
              <main className="mx-auto w-11/12 p-4">
                <Navbar />
                {children}
              </main>
              <Toaster />
            </ThemeProvider>
          </body>
        </TooltipProvider>
      </ClerkProvider>
    </html>
  );
}
