name: CI

on:
  pull_request:
    branches: [main]

jobs:
  format:
    name: format check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Latest version of actions/checkout

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Latest version of actions/setup-node
        with:
          node-version: "node" # Uses the latest stable version of Node.js

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Run Prettier check
        run: npx prettier --check .
        # Use `npx prettier --write .` to auto-fix formatting issues if desired

  lint:
    name: lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Latest version of actions/checkout

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Latest version of actions/setup-node
        with:
          node-version: "node" # Uses the latest stable version of Node.js

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Run ESLint
        run: npm run eslint

  build:
    name: build check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Latest version of actions/checkout

      - name: Set up Node.js
        uses: actions/setup-node@v4 # Latest version of actions/setup-node
        with:
          node-version: "node" # Uses the latest stable version of Node.js

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Build code
        run: npm run build
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ASSISTANT_ID: ${{ secrets.OPENAI_ASSISTANT_ID }}
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          NEXT_PUBLIC_CLERK_SIGN_IN_URL: ${{ secrets.NEXT_PUBLIC_CLERK_SIGN_IN_URL }}
          NEXT_PUBLIC_CLERK_SIGN_UP_URL: ${{ secrets.NEXT_PUBLIC_CLERK_SIGN_UP_URL }}
